## Convenio de Einstein

In [1]:
import numpy as np

a = np.array([[1, 0], [2, -1]])
u = np.array([1, -2])

##### Traza

In [2]:
np.trace(a)

0

In [3]:
np.einsum('ii', a)  # Traza

0

##### Diagonal

In [4]:
np.diag(a)

array([ 1, -1])

In [5]:
np.einsum('ii -> i', a)  # Diagonal

array([ 1, -1])

##### Producto matricial

In [6]:
np.dot(a, a)

array([[1, 0],
       [0, 1]])

In [7]:
np.einsum('ij, jk', a, a)  # Producto matricial

array([[1, 0],
       [0, 1]])

##### Producto matricial por vector

In [8]:
np.dot(a, u)

array([1, 4])

In [9]:
np.einsum('ij, j', a, u)  # Matriz por vector

array([1, 4])

##### Producto escalar

In [10]:
np.dot(u, u)

5

In [11]:
np.einsum('i, i', u, u)  # Producto escalar por sí mismo

5

##### Producto exterior

In [12]:
np.outer(u, u)

array([[ 1, -2],
       [-2,  4]])

In [13]:
np.einsum('i, j', u, u)  # Producto exterior

array([[ 1, -2],
       [-2,  4]])